keys:
  - &admin_laptop age120msgn9wr2d78cmngdkgl3wsg0ftfxauw3slantwh0554h9ayprsdznwxy
  - &admin_desktop age1dk8r7lqc4zrau64z0uqpheevmc2reerzjjwe8pegn6c9rdmjae5stax5zf
  - &server_tower age1pplwtucfg94fpsaxq488qvztqekuzs7y8wzc7nrh3tag0g640a4sph8ny8
  - &server_assistant age127kdzfp3jyenv32fk0hc7ruyrpc5luw7c3v306f6xs39xj87ppdqrfla4h
  - &server_dashboard age1xh3zmwd879d7frp3we3nspga6kgr7ukmdcfyq5m3kj4wdexdtgxqvrene9
creation_rules:
  # Global secrets: Decryptable by your laptop admin key, the tower, AND the pis
  - path_regex: secrets/global\.yaml$
    key_groups:
      - age:
          - *admin_laptop
          - *admin_desktop
          - *server_tower
          - *server_assistant
          - *server_dashboard

  # Tower-specific secrets: Decryptable by your laptop and the tower
  - path_regex: secrets/tower\.yaml$
    key_groups:
      - age:
          - *admin_laptop
          - *admin_desktop
          - *server_tower

  # Pi-specific secrets: Decryptable by your laptop and the pis
  - path_regex: secrets/pi\.yaml$
    key_groups:
      - age:
          - *admin_laptop
          - *admin_desktop
          - *server_assistant
          - *server_dashboard
