[config.wallpaper]
command = "awww"
arguments = ["img"]
set = true

# Quickshell Dynamic Colors
[templates.quickshell]
input_path = '~/.config/matugen/templates/ThemeColors.qml'
output_path = '~/.config/quickshell/ThemeColors.qml'

# Fuzzel Colors
[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

# Niri Theme
[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/theme.kdl'
